%% COMPUTE SPECTRA
specdat = struct;
part = {'all' 'BL' 'PS'};
slce = [1 1024; 1 512; 513 1024];
freq = [4 8 10 16];
frlm = [3 16];
pwlm = [0  14];
mplm = 'absmax';
which_p = 2:3;

for g = which_g
for c = which_c
for h = which_h
    eeg = eval([grp{g}(1) 'EEG' cnd{c} '_H' h]);
    % TO EXAMINE EFFECTS OF TIME:
    eeg2 = eeg;
    for i = 1:numel(eeg)
        eeg(i) = pop_select(eeg(i), 'trial', 1:round(eeg(i).trials / 2));
        eeg2(i) = pop_select(eeg2(i), 'trial'...
                            , round(eeg2(i).trials / 2)+1:eeg2(i).trials);
    end
    eeg2 = pop_mergeset(eeg2, 1:numel(eeg2));
    eeg = pop_mergeset(eeg, 1:numel(eeg));
    
    for p = which_p
        nm = [grp{g} '_' cnd{c} '_H' h '_' part{p} '_'];
        slice = slce(p, 1):slce(p, 2);
        for r = which_r
%             fh = figure('Position', round(lbwh ./ 1.5), 'Visible', 'off');
            specdat.([nm 'early_' ROI{2, r}]) = ...
                spectopo(eeg.data(:, slice, :), numel(slice), 512 ...
                , 'limits', [frlm pwlm]...
                , 'chanlocs', eeg.chanlocs...
                , 'freqrange', frlm...
                , 'plotchans', ROI{1, r}...
                , 'winsize', 512 ...
                , 'overlap', 384 ...
                , 'plot', 'off'...
                , 'title', [nm ROI{2, r} ',ws=512,ol=384']);
            specdat.([nm 'late_' ROI{2, r}]) = ...
                spectopo(eeg2.data(:, slice, :), numel(slice), 512 ...
                , 'limits', [frlm pwlm]...
                , 'chanlocs', eeg2.chanlocs...
                , 'freqrange', frlm...
                , 'plotchans', ROI{1, r}...
                , 'winsize', 512 ...
                , 'overlap', 384 ...
                , 'plot', 'off'...
                , 'title', [nm ROI{2, r} ',ws=512,ol=384']);
%             if ~isfolder(fullfile(oud, 'spectra', ROI{2, r}))
%                 mkdir(fullfile(oud, 'spectra', ROI{2, r}))
%             end
%             print(fh, '-dsvg'...
%                     , fullfile(oud, 'spectra', ROI{2, r}, [nm ROI{2, r}]))
        end
    end
end
end
end


%% OUTPUT SPECTRA VALS
roich = repmat(num2cell(1:8), 1, 4);
names = cellfun(@(x) repmat({x}, 1, 8), {'4Hz' '8Hz' '10Hz' '16Hz'}, 'Un', 0);
names = cellfun(@(x, y) [x num2str(y)], [names{:}], roich, 'Un', 0);
specsub = structfun(@(x) x(:, [4 8 10 16]), specdat, 'Un', 0);
specflat = structfun(@(x) x(:), specsub, 'Un', 0);
specTab = array2table(struct2mat(specflat)...
              , 'VariableNames', fieldnames(specdat)...
              , 'RowNames', names);
writetable(specTab, fullfile(oud, 'spectra', 'tova_spectra.csv')...
              , 'WriteRowNames', true)

clear which_* spec* roich names c g r p h fh nm ROI...
    freq frlm mplm pwlm slce slice part
