function precomp_TOVA(indf)
% ------------------------------------------------

[p, f, e] = fileparts(indf);

[STUDY, ALLEEG] = pop_loadstudy('filename', [f e], 'filepath', p);

std_precomp(STUDY, ALLEEG, {}...
    , 'savetrials', 'on'...
    , 'interp', 'on'...
    , 'recompute', 'on'...
    , 'erp', 'on'...
    , 'erpparams', {'rmbase',[-999 -1] }...
    , 'spec', 'on'...
    , 'specparams', {'specmode','fft','logtrials','off'}...
    , 'erpim', 'on'...
    , 'erpimparams', {'nlines',10,'smoothing',10}...
    , 'ersp', 'on'...
    , 'itc', 'on'...
    , 'erspparams', {'type', 'ersp&itc', 'freqs', [3 30], 'cycles', [3 0.8], 'alpha', 0.05});

