ind = '/home/bcowley/Benslab/CENT/project_TOVA/TOVA-data/paper1';
oud = '/home/bcowley/Benslab/CENT/project_TOVA/ANALYSIS/paper1_extended_anal/ersp';
ROI = [7 15 19 21 23 28 36];
Pz = 19;
group = {'Control' 'ADHD'};
condition = {'inhibition' 'response'};
lbwh = get(0,'ScreenSize');


%% ERPIM x pre-stim alpha phase
cEEG = pop_mergeset( ...
    pop_loadset('filepath', ind, 'filename', 'MERGED_H1_CORRECT_RANDOMISED_CONTROL.set')...
  , pop_loadset('filepath', ind, 'filename', 'MERGED_H2_CORRECT_RANDOMISED_CONTROL.set'));
ix = cellfun(@(x) any(ismember(x, 'cor_rsp')), {cEEG.epoch.eventtype});
cEEGrsp = pop_select(cEEG, 'trial', find(ix));
ix = cellfun(@(x) any(ismember(x, 'cor_inb')), {cEEG.epoch.eventtype});
cEEGinb = pop_select(cEEG, 'trial', find(ix));

aEEG = pop_mergeset( ...
    pop_loadset('filepath', ind, 'filename', 'merged_h1_correct_randomised_adhd.set')...
  , pop_loadset('filepath', ind, 'filename', 'merged_h2_correct_randomised_adhd.set'));
ix = cellfun(@(x) any(ismember(x, 'cor_rsp')), {aEEG.epoch.eventtype});
aEEGrsp = pop_select(aEEG, 'trial', find(ix));
ix = cellfun(@(x) any(ismember(x, 'cor_inb')), {aEEG.epoch.eventtype});
aEEGinb = pop_select(aEEG, 'trial', find(ix));


%% Topoplot the neg+pos peaks
fh = figure('Position', [1 1 lbwh(4) lbwh(3)], 'Color', 'w');
grp = {'c' 'a'};
cnd = {'inb' 'rsp'};

cax = [-2 0];
plt = 1;
itv = 565:616;

for c = 1:2 %conditions across rows
    for g = 1:2 %groups across columns

        subplot(2, 2, plt)
        dat = mean(mean(eval([grp{g} 'EEG' cnd{c}]).data(:, itv, :), 3), 2);
        topoplot(dat, eval([grp{g} 'EEG' cnd{c}]).chanlocs...
            , 'maplimits', cax, 'electrodes', 'on'...
            , 'emarker', {'.','k',[],1}, 'emarker2', {ROI, 'o','m',3,1})
        title(sprintf('%s-%s', group{g}, condition{c}))
        cb = colorbar('EastOutside'); title(cb, '\muV', 'FontSize', 9)

        plt = plt + 1;
    end
    cax = [-3 0.5];
end
% inc = num2str(round((1000 / cEEGrt.srate) * inc - 2));
sgt = sgtitle('Scalp maps at 100-200ms post-stimulus', 'Color', 'r');
% text(-3, -1, ['Scalp maps at ' inc 'ms intervals around RT'], ...
%   'VerticalAlignment', 'bottom', 'HorizontalAlignment', 'center')
% export_fig(fullfile(oud, 'TOVA-topoplots-ERPxRT.pdf'))
print(gcf, '-dsvg', fullfile(oud, 'TOVA-topoplots-ERSP-ownScales'))


%% ERSPs
% TODO REDUCE TO 1 BLOCK OF ERSP CODE USING EVAL() AS ABOVE
cyc = {0 [3 0.5]};
meth = {'FFT' 'wavelet3-05'};
%% ERSP - Pz
for l = 1:numel(cyc)
    TRD = Pz;
    NM = 'Pz';
    
    % Response
    cond = 'response';
    inc = 2:0.5:4;

    for i = 1:numel(inc)
        % [ersp,itc,powbase,times,freqs,sig,itcboot,itcphase]
        [ersp,itc,powbase,times,freqs,erspboot,itcboot]  =  ...
        newtimef(...
            {cEEGrsp.data(TRD,:,:) aEEGrsp.data(TRD,:,:)}...
            , cEEG.pnts...
            , [cEEG.times(1) cEEG.times(end)]...
            , cEEG.srate...
            , cyc{l} ...
            , 'freqs', [inc(i) 30] ...
            , 'nfreqs', 27 ...
            , 'freqscale', 'log'...
            , 'alpha', 0.05...
            , 'baseline', [-1000 -1]...
            , 'commonbase', 'on'...
            , 'trialbase', 'full'...
            , 'title', cellfun(@(x) [x [' - ' cond ' - ' NM]], group, 'Un', 0));

        %TODO - PLAY WITH PARAMS??
        % 'detrend', 'on'
        % 'rmerp', 'on'

        %TODO - scalpmap?
        % which('chanlocs128_pist.elp')

        fh = gcf;
        fh.Position = lbwh;
        print(fh, '-dsvg', fullfile(oud...
        , ['TOVA_ersp_' cond '_' NM '_' meth{l} '_logfreq' strrep(num2str(inc(i)), '.', 'pt') '-30']))
        close
    end

    % Inhibtion
    cond = 'inhibition';
    inc = 2:0.5:4;

    for i = 1:numel(inc)
        newtimef(...
            {cEEGinb.data(TRD,:,:) aEEGinb.data(TRD,:,:)}...
            , cEEG.pnts...
            , [cEEG.times(1) cEEG.times(end)]...
            , cEEG.srate...
            , cyc{l} ...
            , 'freqs', [inc(i) 30] ...
            , 'nfreqs', 27 ...
            , 'freqscale', 'log'...
            , 'alpha', 0.05...
            , 'baseline', [-1000 -1]...
            , 'commonbase', 'on'...
            , 'trialbase', 'full'...
            , 'title', cellfun(@(x) [x [' - ' cond ' - ' NM]], group, 'Un', 0))

        fh = gcf;
        fh.Position = lbwh;
        print(fh, '-dsvg', fullfile(oud...
        , ['TOVA_ersp_' cond '_' NM '_' meth{l} '_logfreq' strrep(num2str(inc(i)), '.', 'pt') '-30']))
        close
    end
end

%% ERSP - ROIs
for l = 1:numel(cyc)
    
    TRD = ROI;
    NM = 'ROI';
    
    % Response
    cond = 'response';
    inc = 2:0.5:4;

    for i = 1:numel(inc)
        newtimef(...
            {mean(cEEGrsp.data(TRD,:,:)) mean(aEEGrsp.data(TRD,:,:))}...
            , cEEG.pnts...
            , [cEEG.times(1) cEEG.times(end)]...
            , cEEG.srate...
            , cyc{l} ...
            , 'freqs', [inc(i) 30] ...
            , 'nfreqs', 27 ...
            , 'freqscale', 'log'...
            , 'alpha', 0.05...
            , 'baseline', [-1000 -1]...
            , 'commonbase', 'on'...
            , 'trialbase', 'full'...
            , 'title', cellfun(@(x) [x [' - ' cond '- ' NM]], group, 'Un', 0))

        fh = gcf;
        fh.Position = lbwh;
        print(fh, '-dsvg', fullfile(oud...
        , ['TOVA_ersp_' cond '_' NM '_' meth{l} '_logfreq' strrep(num2str(inc(i)), '.', 'pt') '-30']))
        close
    end

    % Inhibition
    cond = 'inhibition';
    inc = 2:0.5:4;

    for i = 1:numel(inc)
        newtimef(...
            {mean(cEEGinb.data(TRD,:,:)) mean(aEEGinb.data(TRD,:,:))}...
            , cEEG.pnts...
            , [cEEG.times(1) cEEG.times(end)]...
            , cEEG.srate...
            , cyc{l} ...
            , 'freqs', [inc(i) 30] ...
            , 'nfreqs', 27 ...
            , 'freqscale', 'log'...
            , 'alpha', 0.05...
            , 'baseline', [-1000 -1]...
            , 'commonbase', 'on'...
            , 'trialbase', 'full'...
            , 'title', cellfun(@(x) [x [' - ' cond ' - ' NM]], group, 'Un', 0))

        fh = gcf;
        fh.Position = lbwh;
        print(fh, '-dsvg', fullfile(oud...
        , ['TOVA_ersp_' cond '_' NM '_' meth{l} '_logfreq' strrep(num2str(inc(i)), '.', 'pt') '-30']))
        close
    end
end